
management:
  endpoints:
    web:
      exposure:
        include: "refresh, env"

zuul:
  routes:
  open-mart-api:
    path: /v1/mart/**
    url: http://localhost:8082
    stripPrefix: false
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 10000    
---
spring:
  profiles: imac
  
logging:
  level:
    reactor:
      netty:
        http:
          server:
            AccessLog: DEBUG
    openmart:
      apiserver:
        api: DEBUG
  path: "/Users/sungjun.kim/tank0/logs"
---
spring:
  profiles: macbook
  
logging:
  level:
    reactor:
      netty:
        http:
          server:
            AccessLog: DEBUG
    openmart:
      apiserver:
        api: DEBUG
  path: "/tank0/logs"
---
spring:
  profiles: stg,prd

logging:
  level:
    reactor:
      netty:
        http:
          server:
            AccessLog: ERROR
    openmart:
      apiserver:
        api: ERROR
  path: "/home/ec2-user/tank0/logs"

zuul:
  routes:
  open-mart-api:
    path: /v1/mart/**
    url: http://52.79.138.30:8082
    stripPrefix: false
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 10000
